INSERT INTO users (firstname, lastname, email, password) VALUES ('Рональд', 'Рейнольдс', 'ronald.reynolds66@example.com', 'paco'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Дарлин', 'Эдвардс', 'darlene.edwards15@example.com', 'bricks'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Габриэль', 'Джексон', 'gabriel.jackson91@example.com', 'hjkl'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Дэрил', 'Брайант', 'daryl.bryant94@example.com', 'exodus'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Нил', 'Паркер', 'neil.parker43@example.com', '878787'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Трэвис', 'Райт', 'travis.wright36@example.com', 'smart'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Амелия', 'Кэннеди', 'amelia.kennedy58@example.com', 'beaker'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Айда', 'Дэвис', 'ida.davis80@example.com', 'pepsi1'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Джесси', 'Паттерсон', 'jessie.patterson68@example.com', 'tommy'); 
INSERT INTO users (firstname, lastname, email, password) VALUES ('Деннис', 'Крейг', 'dennis.craig82@example.com', 'coldbeer'); 
COMMIT;